/**
 * All-Star Custom Construction — chatbot knowledge base (100+ entries).
 * Edit questions/answers here; matching uses keywords + question tokens in chatbot-match.ts
 */
import type { ChatbotFaq } from "./chatbot-types";
import { CHATBOT_CITIES, CHATBOT_COMPANY as C, CHATBOT_SERVICES } from "./chatbot-types";

const phone = C.phoneDisplay;
const email = C.email;

/** City-specific FAQs (2 per listed city). */
function faqsByCity(): ChatbotFaq[] {
  return CHATBOT_CITIES.flatMap((city) => {
    const key = city.toLowerCase().replace(/\s+/g, "-");
    return [
      {
        id: `faq-city-${key}-1`,
        category: "serviceArea",
        keywords: [
          `serve ${city}`,
          `work in ${city}`,
          `${city} florida`,
          `${city} fl`,
          `projects in ${city}`,
          city.toLowerCase(),
        ],
        question: `Do you serve ${city}?`,
        answer: `Yes. We regularly complete projects for homeowners in ${city} and surrounding Central Florida areas. Request a free quote and include your address or neighborhood so we can confirm coverage and scheduling.`,
      },
      {
        id: `faq-city-${key}-2`,
        category: "serviceArea",
        keywords: [`${city} contractor`, `outdoor ${city}`, `pavers ${city}`, `concrete ${city}`],
        question: `Do you install pavers or concrete in ${city}?`,
        answer: `We provide concrete, masonry, pavers, and outdoor living work across Central Florida, including ${city}. Share photos and goals in your quote request for the fastest, most accurate follow-up.`,
      },
    ];
  });
}

/** Short service-line FAQs (per core service name). */
function faqsByServiceLine(): ChatbotFaq[] {
  return CHATBOT_SERVICES.map((label, i) => {
    const slug = label.toLowerCase().replace(/[^a-z]+/g, "-");
    const kw = label.toLowerCase();
    return {
      id: `faq-svc-line-${i}-${slug}`,
      category: "services" as const,
      keywords: [kw, `do you ${kw}`, `${kw} install`, `${kw} work`],
      question: `Do you offer ${label.toLowerCase()}?`,
      answer: `Yes — ${label} is one of our core outdoor construction services for Central Florida homeowners. We can review your layout, materials, and goals during a free quote.`,
    };
  });
}

const staticFaqs: ChatbotFaq[] = [
  // —— General (1–10) ——
  {
    id: "faq-g-01",
    category: "general",
    keywords: ["what do you do", "what does all-star", "company do", "about you", "who are you"],
    question: "What does All-Star Custom Construction do?",
    answer: `${C.name} provides custom concrete, masonry, and outdoor living construction for homeowners across ${C.area}: footings, slabs, sidewalks, pavers, masonry features, pergolas, fire pits, decks, fences, and retaining walls. We're backed by ${C.experience} and ${C.serving}.`,
  },
  {
    id: "faq-g-02",
    category: "general",
    keywords: ["where located", "where are you", "office location", "based"],
    question: "Where are you located?",
    answer: `We serve homeowners throughout ${C.area} (including Orlando and surrounding communities). Call ${phone} or request a quote online — we'll confirm service for your address and project type.`,
  },
  {
    id: "faq-g-03",
    category: "serviceArea",
    keywords: ["what areas", "service area", "where serve", "coverage", "regions"],
    question: "What areas do you serve?",
    answer: `We work across ${C.area} — cities we often serve include ${CHATBOT_CITIES.join(", ")}. If your city isn't listed, contact us anyway; availability can depend on project scope and schedule.`,
  },
  {
    id: "faq-g-04",
    category: "trust",
    keywords: ["years experience", "how much experience", "experience"],
    question: "How many years of experience do you have?",
    answer: `Our work is backed by ${C.experience}. That depth helps us plan durable outdoor projects suited to Florida weather and everyday use.`,
  },
  {
    id: "faq-g-05",
    category: "trust",
    keywords: ["how long central florida", "serving central florida", "established"],
    question: "How long have you been serving Central Florida?",
    answer: `We've been proudly serving ${C.area} for ${C.serving}. Homeowners choose us for clear communication, quality workmanship, and lasting outdoor improvements.`,
  },
  {
    id: "faq-g-06",
    category: "general",
    keywords: ["local company", "local contractor", "family"],
    question: "Are you a local company?",
    answer: `Yes — we're focused on ${C.area} homeowners and local outdoor projects. You'll work with a team that understands regional conditions and neighborhood expectations.`,
  },
  {
    id: "faq-g-07",
    category: "services",
    keywords: ["types of projects", "outdoor projects", "what projects"],
    question: "What types of outdoor projects do you handle?",
    answer: `We handle concrete footings, slabs and sidewalks, pavers, masonry, pergolas, fire pits, decks, fences, retaining walls, and related outdoor living improvements.`,
  },
  {
    id: "faq-g-08",
    category: "general",
    keywords: ["homeowners", "residential", "houses"],
    question: "Do you work with homeowners?",
    answer: `Yes — we specialize in residential outdoor construction and masonry for homeowners across ${C.area}.`,
  },
  {
    id: "faq-g-09",
    category: "contact",
    keywords: ["how contact", "reach you", "get in touch"],
    question: "How do I contact you?",
    answer: `Call ${phone}, email ${email}, or use the Contact page to request a free quote. We'll follow up with next steps for your project.`,
  },
  {
    id: "faq-g-10",
    category: "quote",
    keywords: ["request quote", "get quote", "free quote"],
    question: "How do I request a quote?",
    answer: `Use the "Request a Free Quote" button on the site, visit the Contact page, or call ${phone}. Include your name, phone, email, service type, city, and a short project description — photos help too.`,
  },

  // —— Services overview (11–20) ——
  {
    id: "faq-s-11",
    category: "services",
    keywords: ["services offer", "list of services", "what services"],
    question: "What services do you offer?",
    answer: `Concrete footings; slabs and sidewalks; pavers; masonry; pergolas; fire pits; decks; fences; retaining walls — all tailored to your property and goals in ${C.area}.`,
  },
  {
    id: "faq-s-12",
    category: "services",
    keywords: ["concrete work", "pour concrete", "concrete services"],
    question: "Do you do concrete work?",
    answer: `Yes — we pour footings, slabs, sidewalks, and related concrete work for outdoor projects. Scope and finish depend on your site and design.`,
  },
  {
    id: "faq-s-13",
    category: "pavers",
    keywords: ["install pavers", "paver installation"],
    question: "Do you install pavers?",
    answer: `Yes. We install paver patios, walkways, and accents with layouts suited to drainage, use, and Florida conditions.`,
  },
  {
    id: "faq-s-14",
    category: "masonry",
    keywords: ["masonry work", "stone work"],
    question: "Do you do masonry work?",
    answer: `Yes — we build masonry features and walls that add structure and character to outdoor spaces, using methods appropriate for local climate.`,
  },
  {
    id: "faq-s-15",
    category: "pergolas",
    keywords: ["build pergolas", "pergola install"],
    question: "Do you build pergolas?",
    answer: `Yes. Custom pergolas add shade and architectural interest to patios and gathering areas. We can discuss style, size, and structural needs on your quote visit.`,
  },
  {
    id: "faq-s-16",
    category: "firePits",
    keywords: ["fire pit", "firepit"],
    question: "Do you install fire pits?",
    answer: `Yes — we build fire pit areas integrated with hardscape and seating so your backyard is more usable year-round.`,
  },
  {
    id: "faq-s-17",
    category: "decks",
    keywords: ["build decks", "deck construction"],
    question: "Do you build decks?",
    answer: `Yes. We design and build decks for flow, durability, and how you want to use your outdoor space.`,
  },
  {
    id: "faq-s-18",
    category: "fences",
    keywords: ["install fence", "fencing"],
    question: "Do you install fences?",
    answer: `Yes — privacy, perimeter, and boundary fencing with materials chosen for longevity and a clean finish.`,
  },
  {
    id: "faq-s-19",
    category: "retainingWalls",
    keywords: ["retaining wall", "retaining walls"],
    question: "Do you build retaining walls?",
    answer: `Yes. Retaining walls help manage grade, drainage, and usable yard space while improving the look of your landscape.`,
  },
  {
    id: "faq-s-20",
    category: "slabs",
    keywords: ["sidewalks", "slabs", "pour slab"],
    question: "Do you pour sidewalks and slabs?",
    answer: `Yes — new sidewalks, utility slabs, and patio-style slabs are common requests. We'll assess prep, drainage, and finish during your estimate.`,
  },

  // —— Footings (21–30) ——
  {
    id: "faq-f-21",
    category: "footings",
    keywords: ["what are footings", "footing meaning"],
    question: "What are concrete footings?",
    answer: `Footings are reinforced concrete bases that spread structural loads into the ground. They're often used under pergolas, fences, and other features that need stable support.`,
  },
  {
    id: "faq-f-22",
    category: "footings",
    keywords: ["footings pergola", "pergola footing"],
    question: "Do I need footings for a pergola?",
    answer: `Many pergolas need proper footings for safety and longevity. The right approach depends on size, attachment, and local conditions — we'll assess during your quote.`,
  },
  {
    id: "faq-f-23",
    category: "footings",
    keywords: ["footings fence", "fence footing"],
    question: "Do you pour footings for fences?",
    answer: `Yes, when the design or soil conditions call for it. We can recommend the right support for your fence line and gates.`,
  },
  {
    id: "faq-f-24",
    category: "footings",
    keywords: ["structural outdoor", "structural projects"],
    question: "Can you do footings for structural outdoor projects?",
    answer: `Yes — footings for outdoor structures are part of our concrete work. We'll align the plan with your goals and practical requirements.`,
  },
  {
    id: "faq-f-25",
    category: "footings",
    keywords: ["need new footings", "replace footing"],
    question: "How do I know if I need new footings?",
    answer: `Signs can include movement, cracking, or planned upgrades that add load. An on-site look during an estimate is the best way to know what's needed.`,
  },
  {
    id: "faq-f-26",
    category: "footings",
    keywords: ["footings included", "part of project"],
    question: "Are footings included in some projects?",
    answer: `Footings are often included when they're required for the feature we're building (for example, a pergola or heavy gate). Your written scope will spell it out.`,
  },
  {
    id: "faq-f-27",
    category: "footings",
    keywords: ["inspect footing", "check footings"],
    question: "Do you inspect footing needs before the project?",
    answer: `Yes — we review site conditions and structure needs as part of planning so the base work matches the finished build.`,
  },
  {
    id: "faq-f-28",
    category: "footings",
    keywords: ["durability footings", "long term footings"],
    question: "Can footings help with long-term durability?",
    answer: `Proper footings reduce settling and movement over time, which protects your investment in fences, pergolas, and other features.`,
  },
  {
    id: "faq-f-29",
    category: "footings",
    keywords: ["local requirements", "code", "permit"],
    question: "Do footings need to meet local requirements?",
    answer: `Projects may need to follow local codes and permit rules depending on scope and jurisdiction. We'll discuss what's applicable when we review your job.`,
  },
  {
    id: "faq-f-30",
    category: "footings",
    keywords: ["quote footing", "estimate footing"],
    question: "Can I get a quote for footing work?",
    answer: `Absolutely — request a free quote or call ${phone} and describe the structure or fence line you have in mind.`,
  },

  // —— Slabs & sidewalks (31–40) ——
  {
    id: "faq-sl-31",
    category: "slabs",
    keywords: ["pour slabs", "concrete slab"],
    question: "Do you pour concrete slabs?",
    answer: `Yes — for patios, utility areas, and other outdoor uses. Size, thickness, and reinforcement depend on use and soil conditions.`,
  },
  {
    id: "faq-sl-32",
    category: "slabs",
    keywords: ["install sidewalk", "new sidewalk"],
    question: "Do you install sidewalks?",
    answer: `Yes. New or replacement sidewalks improve safety, access, and curb appeal.`,
  },
  {
    id: "faq-sl-33",
    category: "slabs",
    keywords: ["replace sidewalk", "old sidewalk"],
    question: "Can you replace an old sidewalk?",
    answer: `Often yes — we'll evaluate removal, base, and drainage as part of your estimate.`,
  },
  {
    id: "faq-sl-34",
    category: "slabs",
    keywords: ["backyard slab", "patio slab"],
    question: "Can you pour a slab for a backyard project?",
    answer: `Yes. We can help size and place a slab to support furniture, grills, or future structures.`,
  },
  {
    id: "faq-sl-35",
    category: "slabs",
    keywords: ["florida weather concrete", "heat rain concrete"],
    question: "Are concrete slabs good for Florida weather?",
    answer: `With proper prep, drainage, and mix practices, concrete performs well in Florida. We focus on details that hold up in heat and rain.`,
  },
  {
    id: "faq-sl-36",
    category: "slabs",
    keywords: ["curb appeal walkway", "walkway appeal"],
    question: "Can you improve curb appeal with a new walkway?",
    answer: `Yes — clean sidewalks and defined paths make a strong first impression and improve everyday use.`,
  },
  {
    id: "faq-sl-37",
    category: "slabs",
    keywords: ["remove old concrete", "tear out concrete"],
    question: "Do you remove old concrete?",
    answer: `Removal can be included when it's part of the agreed scope. We'll note haul-off and prep in your project plan.`,
  },
  {
    id: "faq-sl-38",
    category: "timeline",
    keywords: ["slab how long", "sidewalk timeline"],
    question: "How long does a slab or sidewalk project usually take?",
    answer: `Timelines vary with size, weather, curing, and site access. We'll outline realistic phases after we see your property.`,
  },
  {
    id: "faq-sl-39",
    category: "slabs",
    keywords: ["slab size", "plan slab"],
    question: "Can you help plan the right slab size?",
    answer: `Yes — we'll discuss how you want to use the space and recommend practical dimensions and placement.`,
  },
  {
    id: "faq-sl-40",
    category: "quote",
    keywords: ["estimate slab", "quote sidewalk"],
    question: "How do I request an estimate for a slab or sidewalk?",
    answer: `Request a free quote on the Contact page or call ${phone}. Photos and approximate dimensions help us respond faster.`,
  },

  // —— Pavers (41–50) ——
  {
    id: "faq-p-41",
    category: "pavers",
    keywords: ["paver patio", "patio pavers"],
    question: "Do you install paver patios?",
    answer: `Yes — custom paver patios for dining, lounging, and entertaining, with patterns and colors to match your style.`,
  },
  {
    id: "faq-p-42",
    category: "pavers",
    keywords: ["paver walkway", "walkway pavers"],
    question: "Do you install paver walkways?",
    answer: `Yes. Walkways connect spaces and improve flow while handling foot traffic and drainage.`,
  },
  {
    id: "faq-p-43",
    category: "pavers",
    keywords: ["driveway accent", "paver border"],
    question: "Do you do paver driveway accents?",
    answer: `Yes — borders and accents can elevate a driveway or entry without a full replacement.`,
  },
  {
    id: "faq-p-44",
    category: "pavers",
    keywords: ["pavers florida", "pavers weather"],
    question: "Are pavers good for Florida weather?",
    answer: `Pavers are a popular choice in Florida when installed with proper base, edge restraint, and drainage.`,
  },
  {
    id: "faq-p-45",
    category: "pavers",
    keywords: ["benefits pavers", "why pavers"],
    question: "What are the benefits of pavers?",
    answer: `Design flexibility, strong curb appeal, and the ability to address small areas without replacing everything at once.`,
  },
  {
    id: "faq-p-46",
    category: "pavers",
    keywords: ["curb appeal pavers"],
    question: "Can pavers improve curb appeal?",
    answer: `Definitely — clean patterns and defined outdoor “rooms” make a property feel finished and well maintained.`,
  },
  {
    id: "faq-p-47",
    category: "pavers",
    keywords: ["custom paver layout"],
    question: "Can you build custom paver layouts?",
    answer: `Yes — we can tailor shape, pattern, and borders to your space and how you use it.`,
  },
  {
    id: "faq-p-48",
    category: "pavers",
    keywords: ["paver pattern", "choose pattern"],
    question: "Do you help choose paver patterns?",
    answer: `We'll walk through options that fit your architecture, budget, and maintenance preferences.`,
  },
  {
    id: "faq-p-49",
    category: "pavers",
    keywords: ["entertaining pavers", "hosting patio"],
    question: "Are pavers good for entertaining spaces?",
    answer: `Yes — level, defined patio areas make seating, cooking, and gathering easier and more comfortable.`,
  },
  {
    id: "faq-p-50",
    category: "quote",
    keywords: ["quote pavers", "paver estimate"],
    question: "Can I get a quote for paver installation?",
    answer: `Request a quote online or call ${phone}. Approximate dimensions and photos speed things up.`,
  },

  // —— Masonry (51–60) ——
  {
    id: "faq-m-51",
    category: "masonry",
    keywords: ["block work", "cinder block"],
    question: "Do you do block work?",
    answer: `Yes — block and related masonry for walls and features when it fits your design.`,
  },
  {
    id: "faq-m-52",
    category: "masonry",
    keywords: ["brick work", "brick veneer"],
    question: "Do you do brick work?",
    answer: `We handle brick and masonry-style features as part of outdoor projects — tell us what you have in mind on your quote request.`,
  },
  {
    id: "faq-m-53",
    category: "masonry",
    keywords: ["masonry services list"],
    question: "What masonry services do you offer?",
    answer: `Feature walls, structural and decorative masonry elements tied to patios, entries, and landscape plans.`,
  },
  {
    id: "faq-m-54",
    category: "masonry",
    keywords: ["decorative structural masonry"],
    question: "Can masonry be decorative and structural?",
    answer: `Yes — some walls both define space and carry load or retain soil. We'll match the build to the engineering needs.`,
  },
  {
    id: "faq-m-55",
    category: "masonry",
    keywords: ["masonry walls"],
    question: "Do you build masonry walls?",
    answer: `Yes — for definition, seating, planters, and structural needs depending on the project.`,
  },
  {
    id: "faq-m-56",
    category: "masonry",
    keywords: ["upgrade outdoor masonry"],
    question: "Can you upgrade an outdoor area with masonry?",
    answer: `Masonry can refresh entries, fire features, and patio edges. We'll suggest options that fit your budget.`,
  },
  {
    id: "faq-m-57",
    category: "masonry",
    keywords: ["masonry durable florida"],
    question: "Is masonry durable in Florida?",
    answer: `With correct materials and installation, masonry holds up well. We account for moisture, heat, and long-term wear.`,
  },
  {
    id: "faq-m-58",
    category: "masonry",
    keywords: ["design masonry feature"],
    question: "Can you help design a masonry feature?",
    answer: `We'll collaborate on proportions, finishes, and how the feature ties into pavers or concrete nearby.`,
  },
  {
    id: "faq-m-59",
    category: "masonry",
    keywords: ["custom masonry"],
    question: "Do you do custom masonry projects?",
    answer: `Yes — share inspiration photos and measurements when you request your quote.`,
  },
  {
    id: "faq-m-60",
    category: "quote",
    keywords: ["masonry pricing", "masonry quote"],
    question: "How do I request masonry pricing?",
    answer: `Use the contact form or call ${phone}. Site photos and approximate dimensions help us narrow options before we meet.`,
  },

  // —— Pergolas (61–70) ——
  {
    id: "faq-pg-61",
    category: "pergolas",
    keywords: ["build pergola"],
    question: "Do you build pergolas?",
    answer: `Yes — custom pergolas for shade, style, and outdoor living.`,
  },
  {
    id: "faq-pg-62",
    category: "pergolas",
    keywords: ["custom pergola"],
    question: "Can you build a custom pergola?",
    answer: `Absolutely — size, posts, rafters, and finishes can be tailored to your patio and home.`,
  },
  {
    id: "faq-pg-63",
    category: "pergolas",
    keywords: ["pergola shade"],
    question: "Are pergolas good for shade?",
    answer: `They provide partial shade and structure; coverage depends on design and optional additions you choose.`,
  },
  {
    id: "faq-pg-64",
    category: "pergolas",
    keywords: ["backyard pergola improve"],
    question: "Can a pergola improve my backyard?",
    answer: `Yes — it anchors seating areas and makes the yard feel like an outdoor room.`,
  },
  {
    id: "faq-pg-65",
    category: "pergolas",
    keywords: ["pergola footings need"],
    question: "Do pergolas require footings?",
    answer: `Often yes for freestanding structures. We'll confirm what's needed for your design and soil.`,
  },
  {
    id: "faq-pg-66",
    category: "pergolas",
    keywords: ["pergola entertaining"],
    question: "Can you build pergolas for entertaining spaces?",
    answer: `Yes — we size and place them to work with grills, seating, and traffic flow.`,
  },
  {
    id: "faq-pg-67",
    category: "pergolas",
    keywords: ["pergola style"],
    question: "Can I choose the pergola style?",
    answer: `We'll review traditional, modern, and hybrid looks that match your home.`,
  },
  {
    id: "faq-pg-68",
    category: "pergolas",
    keywords: ["pergola existing patio"],
    question: "Can you add a pergola to an existing patio?",
    answer: `Often yes — attachment and support details depend on the patio and structure. We'll evaluate on site.`,
  },
  {
    id: "faq-pg-69",
    category: "timeline",
    keywords: ["pergola how long"],
    question: "How long does a pergola project take?",
    answer: `Duration varies with size, finishes, and weather. We'll give a project-specific timeline with your estimate.`,
  },
  {
    id: "faq-pg-70",
    category: "quote",
    keywords: ["pergola estimate"],
    question: "Can I request a pergola estimate?",
    answer: `Yes — quote request online or call ${phone}.`,
  },

  // —— Fire pits (71–80) ——
  {
    id: "faq-fp-71",
    category: "firePits",
    keywords: ["backyard fire pit"],
    question: "Do you build backyard fire pits?",
    answer: `Yes — fire pit areas that become a natural gathering spot.`,
  },
  {
    id: "faq-fp-72",
    category: "firePits",
    keywords: ["custom fire pit"],
    question: "Can you build a custom fire pit area?",
    answer: `Yes — shape, seating, and hardscape ties are planned around how you'll use the space.`,
  },
  {
    id: "faq-fp-73",
    category: "firePits",
    keywords: ["fire pit entertaining"],
    question: "Are fire pits good for outdoor entertaining?",
    answer: `They're one of the most requested upgrades for evening use and hosting.`,
  },
  {
    id: "faq-fp-74",
    category: "firePits",
    keywords: ["fire pit patio design"],
    question: "Can a fire pit be built into a patio design?",
    answer: `Yes — integrated designs with pavers or masonry are common.`,
  },
  {
    id: "faq-fp-75",
    category: "firePits",
    keywords: ["fire pit layout ideas"],
    question: "Do you help with fire pit layout ideas?",
    answer: `We'll discuss seating distance, wind, and traffic so the layout feels natural.`,
  },
  {
    id: "faq-fp-76",
    category: "firePits",
    keywords: ["fire pit pavers masonry"],
    question: "Can fire pits be added with pavers or masonry?",
    answer: `Yes — we often combine fire features with surrounding hardscape.`,
  },
  {
    id: "faq-fp-77",
    category: "firePits",
    keywords: ["complete fire pit area"],
    question: "What makes a fire pit area feel complete?",
    answer: `Comfortable seating, safe clearances, lighting nearby, and surfacing that handles heat and spills.`,
  },
  {
    id: "faq-fp-78",
    category: "firePits",
    keywords: ["decorative fire pit"],
    question: "Can you build a decorative fire pit feature?",
    answer: `Yes — caps, stone faces, and shapes can match your style.`,
  },
  {
    id: "faq-fp-79",
    category: "firePits",
    keywords: ["resale fire pit"],
    question: "Is a fire pit a good upgrade for resale appeal?",
    answer: `Outdoor living upgrades often help presentation; exact impact varies by market and buyer.`,
  },
  {
    id: "faq-fp-80",
    category: "quote",
    keywords: ["quote fire pit"],
    question: "How do I get a quote for a fire pit?",
    answer: `Request a quote or call ${phone} with approximate size and location in your yard.`,
  },

  // —— Decks (81–90) ——
  {
    id: "faq-d-81",
    category: "decks",
    keywords: ["build decks"],
    question: "Do you build decks?",
    answer: `Yes — backyard decks sized for dining, lounging, and access.`,
  },
  {
    id: "faq-d-82",
    category: "decks",
    keywords: ["low maintenance deck", "composite deck"],
    question: "Can you build a low-maintenance deck?",
    answer: `We can discuss wood and composite options and what fits your maintenance preferences.`,
  },
  {
    id: "faq-d-83",
    category: "decks",
    keywords: ["expand outdoor living deck"],
    question: "Can a deck expand my outdoor living space?",
    answer: `Decks add usable area for furniture and traffic without expanding your home's footprint.`,
  },
  {
    id: "faq-d-84",
    category: "decks",
    keywords: ["backyard decks"],
    question: "Do you build decks for backyards?",
    answer: `Yes — that's a core use case for our deck work.`,
  },
  {
    id: "faq-d-85",
    category: "decks",
    keywords: ["deck size layout"],
    question: "Can you help plan deck size and layout?",
    answer: `We'll align dimensions with doors, stairs, views, and how you entertain.`,
  },
  {
    id: "faq-d-86",
    category: "decks",
    keywords: ["decks entertaining"],
    question: "Are decks good for entertaining?",
    answer: `Yes — they create a level platform for guests and furniture.`,
  },
  {
    id: "faq-d-87",
    category: "decks",
    keywords: ["custom deck design"],
    question: "Can you build a custom deck design?",
    answer: `Yes — rails, stairs, and levels can be customized.`,
  },
  {
    id: "faq-d-88",
    category: "decks",
    keywords: ["benefits new deck"],
    question: "What are the benefits of a new deck?",
    answer: `Better access, more usable space, and a refreshed look for your exterior.`,
  },
  {
    id: "faq-d-89",
    category: "timeline",
    keywords: ["deck construction time"],
    question: "How long does deck construction usually take?",
    answer: `Depends on size, height, and details. We'll outline phases after a site review.`,
  },
  {
    id: "faq-d-90",
    category: "quote",
    keywords: ["estimate deck"],
    question: "Can I request an estimate for a deck?",
    answer: `Yes — online quote or ${phone}.`,
  },

  // —— Fences (91–100) ——
  {
    id: "faq-fc-91",
    category: "fences",
    keywords: ["install fences"],
    question: "Do you install fences?",
    answer: `Yes — privacy and perimeter fencing for homeowners.`,
  },
  {
    id: "faq-fc-92",
    category: "fences",
    keywords: ["privacy fence"],
    question: "Do you install privacy fences?",
    answer: `Yes — common for backyards and pool areas where allowed.`,
  },
  {
    id: "faq-fc-93",
    category: "fences",
    keywords: ["fence security privacy"],
    question: "Can a fence improve security and privacy?",
    answer: `A solid fence line helps define your yard and reduce sightlines from neighbors or streets.`,
  },
  {
    id: "faq-fc-94",
    category: "fences",
    keywords: ["replace fence"],
    question: "Can you replace an old fence?",
    answer: `Yes — we'll discuss removal, posts, and gates as part of scope.`,
  },
  {
    id: "faq-fc-95",
    category: "fences",
    keywords: ["fence layout"],
    question: "Do you help with fence layout?",
    answer: `We'll review property lines, gates, and slopes during planning.`,
  },
  {
    id: "faq-fc-96",
    category: "fences",
    keywords: ["fence curb appeal"],
    question: "Can a fence improve curb appeal?",
    answer: `A clean, straight fence with a good gate can sharpen the look of your property.`,
  },
  {
    id: "faq-fc-97",
    category: "fences",
    keywords: ["before fence consider"],
    question: "What should I consider before installing a fence?",
    answer: `Boundaries, HOA rules, gate locations, height needs, and material maintenance.`,
  },
  {
    id: "faq-fc-98",
    category: "fences",
    keywords: ["durable fence materials"],
    question: "Do you install durable fence materials?",
    answer: `We focus on materials suited to Florida sun and rain for your budget.`,
  },
  {
    id: "faq-fc-99",
    category: "quote",
    keywords: ["fence estimate"],
    question: "Can I request a fence estimate?",
    answer: `Yes — quote form or call ${phone} with approximate linear feet if you know them.`,
  },
  {
    id: "faq-fc-100",
    category: "fences",
    keywords: ["perimeter fencing"],
    question: "Do you install perimeter fencing?",
    answer: `Yes — full runs and partial replacements depending on your needs.`,
  },

  // —— Retaining walls (101–110) ——
  {
    id: "faq-rw-101",
    category: "retainingWalls",
    keywords: ["build retaining wall"],
    question: "Do you build retaining walls?",
    answer: `Yes — for grade changes, usable terraces, and cleaner landscape lines.`,
  },
  {
    id: "faq-rw-102",
    category: "retainingWalls",
    keywords: ["retaining wall drainage"],
    question: "Can retaining walls help with drainage?",
    answer: `Proper walls include drainage thought — we plan for water behind and through the system.`,
  },
  {
    id: "faq-rw-103",
    category: "retainingWalls",
    keywords: ["yard stability slope"],
    question: "Can retaining walls improve yard stability?",
    answer: `They help manage slopes and soil movement when engineered for the height and load.`,
  },
  {
    id: "faq-rw-104",
    category: "retainingWalls",
    keywords: ["decorative retaining"],
    question: "Are retaining walls decorative too?",
    answer: `Yes — block style, cap, and curves can complement your home.`,
  },
  {
    id: "faq-rw-105",
    category: "retainingWalls",
    keywords: ["sloped yard wall"],
    question: "Can you build retaining walls for sloped yards?",
    answer: `That's a common reason homeowners call us — tiered or single walls depending on grade.`,
  },
  {
    id: "faq-rw-106",
    category: "retainingWalls",
    keywords: ["retaining wall design"],
    question: "Do retaining walls improve outdoor design?",
    answer: `They add structure and can frame planting beds or patios.`,
  },
  {
    id: "faq-rw-107",
    category: "retainingWalls",
    keywords: ["landscape organize wall"],
    question: "Can retaining walls help organize a landscape?",
    answer: `Yes — flat terraces make mowing, planting, and play areas easier.`,
  },
  {
    id: "faq-rw-108",
    category: "retainingWalls",
    keywords: ["need retaining wall"],
    question: "How do I know if I need a retaining wall?",
    answer: `Erosion, slope toward the home, or unusable hills are signs. We'll advise on site.`,
  },
  {
    id: "faq-rw-109",
    category: "quote",
    keywords: ["retaining wall quote"],
    question: "Do you offer retaining wall quotes?",
    answer: `Yes — request a quote with photos of the slope or existing wall.`,
  },
  {
    id: "faq-rw-110",
    category: "retainingWalls",
    keywords: ["retaining wall durability"],
    question: "Are retaining walls built for long-term durability?",
    answer: `We focus on base, drainage, and block choice so walls perform over time.`,
  },

  // —— Service area extras (121–125) ——
  {
    id: "faq-a-121",
    category: "serviceArea",
    keywords: ["city not listed", "not listed", "my town"],
    question: "My city is not listed. Can you still help?",
    answer: `Often yes — reach out with your address and project type. Coverage can depend on distance and schedule.`,
  },
  {
    id: "faq-a-122",
    category: "serviceArea",
    keywords: ["across central florida", "whole region"],
    question: "Do you work across Central Florida?",
    answer: `Yes — ${C.area} is our focus, from metro Orlando to many surrounding communities.`,
  },
  {
    id: "faq-a-123",
    category: "serviceArea",
    keywords: ["area covered", "know if covered"],
    question: "How do I know if my area is covered?",
    answer: `Call ${phone} or submit a quote with your city — we'll confirm quickly.`,
  },
  {
    id: "faq-a-124",
    category: "serviceArea",
    keywords: ["nearby not listed"],
    question: "Can I contact you if I'm nearby but not listed?",
    answer: `Please do — many projects are just outside the cities named on the site.`,
  },
  {
    id: "faq-a-125",
    category: "serviceArea",
    keywords: ["scope service area"],
    question: "Do service areas depend on project scope?",
    answer: `Sometimes larger or specialized projects extend how far we schedule — ask when you inquire.`,
  },

  // —— Quote / lead (126–135) ——
  {
    id: "faq-q-126",
    category: "quote",
    keywords: ["free quote how"],
    question: "How do I request a free quote?",
    answer: `Use the Contact page form or call ${phone}. There's no pressure — just clear next steps.`,
  },
  {
    id: "faq-q-127",
    category: "quote",
    keywords: ["information estimate", "what to include quote"],
    question: "What information should I include for an estimate?",
    answer: `Name, phone, email, city, service type, and a short description. Photos and approximate sizes help a lot.`,
  },
  {
    id: "faq-q-128",
    category: "contact",
    keywords: ["call instead", "rather call"],
    question: "Can I call instead of using the form?",
    answer: `Absolutely — ${phone} is the fastest way to reach us for many homeowners.`,
  },
  {
    id: "faq-q-129",
    category: "contact",
    keywords: ["best way contact"],
    question: "What is the best way to contact you?",
    answer: `Phone for urgent questions; the quote form when you want to attach details and photos.`,
  },
  {
    id: "faq-q-130",
    category: "quote",
    keywords: ["no pressure", "pushy"],
    question: "Do you offer no-pressure estimates?",
    answer: `Yes — we're here to give clear information so you can decide on your timeline.`,
  },
  {
    id: "faq-q-131",
    category: "quote",
    keywords: ["send details online"],
    question: "Can I send project details online?",
    answer: `Yes — the Contact form is built for that. You can also email ${email}.`,
  },
  {
    id: "faq-q-132",
    category: "quote",
    keywords: ["include photos", "pictures project"],
    question: "Should I include photos of my project?",
    answer: `Photos help us understand access, existing conditions, and scope before we visit.`,
  },
  {
    id: "faq-q-133",
    category: "quote",
    keywords: ["multiple questions"],
    question: "Can I ask multiple project questions?",
    answer: `Yes — list them in your message or walk through them on a call.`,
  },
  {
    id: "faq-q-134",
    category: "scheduling",
    keywords: ["follow up how fast", "how quickly respond"],
    question: "How quickly can someone follow up?",
    answer: `We aim to respond promptly during business hours. Calling ${phone} is fastest for time-sensitive questions.`,
  },
  {
    id: "faq-q-135",
    category: "quote",
    keywords: ["start project", "get started"],
    question: "How do I start my project?",
    answer: `Request a quote or call us. We'll discuss scope, schedule a look if needed, and outline next steps.`,
  },

  // —— Pricing / timeline / trust (136–145) ——
  {
    id: "faq-pr-136",
    category: "quote",
    keywords: ["how much cost", "project cost", "ballpark"],
    question: "How much does a project cost?",
    answer: `Pricing depends on size, materials, site conditions, and scope. We don't quote exact prices here — request a free estimate so we can review your property.`,
  },
  {
    id: "faq-pr-137",
    category: "quote",
    keywords: ["prices depend size"],
    question: "Do prices depend on project size?",
    answer: `Yes — larger areas, taller walls, and premium materials all affect the total. We'll break it down in your quote.`,
  },
  {
    id: "faq-pr-138",
    category: "quote",
    keywords: ["quote custom"],
    question: "Can you quote custom projects?",
    answer: `Yes — custom is our specialty. Detailed notes and photos help us prepare.`,
  },
  {
    id: "faq-pr-139",
    category: "timeline",
    keywords: ["typical project take", "how long project"],
    question: "How long does a typical project take?",
    answer: `Timelines vary by project size, materials, weather, and crew schedule. We'll give a realistic range after we understand scope.`,
  },
  {
    id: "faq-pr-140",
    category: "timeline",
    keywords: ["timeline scope materials"],
    question: "Does timeline depend on scope and materials?",
    answer: `Yes — lead times for materials and complexity of the build both matter.`,
  },
  {
    id: "faq-pr-141",
    category: "trust",
    keywords: ["quality workmanship"],
    question: "Do you focus on quality workmanship?",
    answer: `Yes — clean finishes, solid prep, and communication are central to how we work.`,
  },
  {
    id: "faq-pr-142",
    category: "trust",
    keywords: ["what makes different", "why different"],
    question: "What makes your company different?",
    answer: `${C.experience}, ${C.serving}, and a hands-on approach to outdoor builds that need to survive Florida conditions.`,
  },
  {
    id: "faq-pr-143",
    category: "trust",
    keywords: ["why choose all-star", "why hire you"],
    question: "Why should I choose All-Star?",
    answer: `Local focus, broad outdoor construction skills, and a process built around clear estimates and durable results.`,
  },
  {
    id: "faq-pr-144",
    category: "general",
    keywords: ["plan approach property"],
    question: "Do you help plan the right approach for my property?",
    answer: `Yes — we recommend solutions based on layout, drainage, and how you want to use the space.`,
  },
  {
    id: "faq-pr-145",
    category: "trust",
    keywords: ["communication during project"],
    question: "Do you offer clear communication during projects?",
    answer: `We prioritize updates and straightforward answers so you know what to expect.`,
  },

  // —— Contact CTAs (146–150) ——
  {
    id: "faq-c-146",
    category: "contact",
    keywords: ["phone number", "what number", "call number"],
    question: "What phone number should I call?",
    answer: `Call us at ${phone}.`,
  },
  {
    id: "faq-c-147",
    category: "contact",
    keywords: ["what email", "email address"],
    question: "What email should I use?",
    answer: `${email} — great for sending photos and written details.`,
  },
  {
    id: "faq-c-148",
    category: "contact",
    keywords: ["talk someone", "speak to someone"],
    question: "Can I talk to someone about my project?",
    answer: `Yes — call ${phone} and we'll discuss your goals and scheduling.`,
  },
  {
    id: "faq-c-149",
    category: "contact",
    keywords: ["calling faster than form"],
    question: "Is calling faster than using the form?",
    answer: `Often yes for quick questions. The form is best when you want to attach photos and detailed notes.`,
  },
  {
    id: "faq-c-150",
    category: "contact",
    keywords: ["get started today", "start today"],
    question: "How do I get started today?",
    answer: `Call ${phone} or submit the free quote form — either way we'll help you take the next step.`,
  },

  // —— Extra: materials, maintenance, scheduling ——
  {
    id: "faq-x-151",
    category: "materials",
    keywords: ["what materials", "materials use"],
    question: "What materials do you work with?",
    answer: `Concrete, pavers, masonry products, wood and composite decking materials, fencing systems, and retaining wall blocks — matched to your project.`,
  },
  {
    id: "faq-x-152",
    category: "materials",
    keywords: ["choose materials", "help pick materials"],
    question: "Do you help homeowners choose materials?",
    answer: `Yes — we explain tradeoffs for durability, maintenance, and look.`,
  },
  {
    id: "faq-x-153",
    category: "maintenance",
    keywords: ["maintain pavers", "paver maintenance"],
    question: "How do I maintain pavers?",
    answer: `Periodic sweeping, joint sand as needed, and prompt cleanup of spills. We'll note care tips for your specific install.`,
  },
  {
    id: "faq-x-154",
    category: "maintenance",
    keywords: ["seal concrete", "seal pavers"],
    question: "Should I seal concrete or pavers?",
    answer: `Sealing can help in some cases; it's not always required. We'll advise based on product and exposure.`,
  },
  {
    id: "faq-x-155",
    category: "scheduling",
    keywords: ["when start", "availability", "book project"],
    question: "When can you start my project?",
    answer: `Start dates depend on current schedule and material lead times. We'll discuss timing when you approve the scope.`,
  },
  {
    id: "faq-x-156",
    category: "scheduling",
    keywords: ["weather delay", "rain delay"],
    question: "What if weather delays my job?",
    answer: `Outdoor work follows safe, workable conditions. We'll communicate rescheduling if weather affects your dates.`,
  },
  {
    id: "faq-x-157",
    category: "general",
    keywords: ["licensed insured", "license"],
    question: "Are you licensed and insured?",
    answer: `For official credentials and documentation, please call ${phone} — we're happy to provide what's appropriate for your request.`,
  },
  {
    id: "faq-x-158",
    category: "quote",
    keywords: ["deposit", "payment"],
    question: "Do you require a deposit?",
    answer: `Payment terms are reviewed with your written scope and estimate. Ask during your quote conversation.`,
  },
  {
    id: "faq-x-159",
    category: "general",
    keywords: ["warranty", "guarantee work"],
    question: "Do you guarantee your work?",
    answer: `We stand behind quality workmanship. Specific warranty or guarantee language is discussed with your project agreement.`,
  },
  {
    id: "faq-x-160",
    category: "services",
    keywords: ["pool deck", "around pool"],
    question: "Do you work around pools?",
    answer: `Outdoor hardscape near pools is common for us — mention pool clearance and decking goals in your quote request.`,
  },
];

export const chatbotFaqs: ChatbotFaq[] = [
  ...staticFaqs,
  ...faqsByCity(),
  ...faqsByServiceLine(),
];
